version: '3.3'
services:
    proxy:
        build:
            context: ./
            dockerfile: docker/frontend/Dockerfile
            args:
                REACT_APP_BACKEND_URL: $BACKEND_URL
                REACT_APP_STATIC_URL: $STATIC_URL
        ports:
            - 80:80
        depends_on:
            - backend
        restart: always
        environment:
            BACKEND_URL: $BACKEND_URL
            STATIC_URL: $STATIC_URL
    backend:
        build:
            context: ./
            dockerfile: docker/backend/Dockerfile
        environment:
            FRONTEND_URL: $FRONTEND_URL
            PYTHONPATH: /app/backend/
            COEFDATAFILE: "data/Cotations CI - Moyennes.csv"
        restart: always


